import MySQLdb

db = MySQLdb.connect(host="db", user="koha_kohadev", passwd="password", db="koha_kohadev", port=3306, charset='utf8')
cursor = db.cursor()

tag_dict = {
    "000": "Đầu biểu ghi (Leader)",
    "001": "Số kiểm soát",
    "003": "Chỉ danh số kiểm soát",
    "005": "Ngày giờ giao dịch gần nhất",
    "006": "Các yếu tố độ dài cố định - Đặc trưng bổ sung",
    "007": "Trường cố định mô tả vật lý - Thông tin chung",
    "008": "Các yếu tố độ dài cố định - Thông tin chung",
    "010": "Số kiểm soát LC",
    "015": "Số thư mục quốc gia",
    "016": "Số kiểm soát cơ quan thư mục quốc gia",
    "020": "Số ISBN",
    "022": "Số ISSN",
    "024": "Mã hoặc số tiêu chuẩn khác",
    "027": "Số báo cáo kỹ thuật chuẩn",
    "028": "Số của nhà phát hành",
    "035": "Số kiểm soát hệ thống",
    "037": "Nguồn bổ sung",
    "040": "Nguồn biên mục",
    "041": "Mã ngôn ngữ",
    "045": "Khoảng thời gian của nội dung",
    "047": "Mã hình thức tác phẩm âm nhạc",
    "048": "Mã nhạc cụ hoặc giọng hát",
    "050": "Ký hiệu phân loại LC",
    "074": "Số tài liệu GPO",
    "082": "Ký hiệu phân loại DDC",
    "086": "Ký hiệu phân loại tài liệu chính phủ",
    "090": "Ký hiệu phân loại nội bộ",
    "100": "Tác giả chính - Tên cá nhân",
    "110": "Tác giả chính - Tên tập thể",
    "111": "Tác giả chính - Tên hội nghị",
    "130": "Tác giả chính - Nhan đề đồng nhất",
    "240": "Nhan đề đồng nhất",
    "245": "Nhan đề và thông tin trách nhiệm",
    "246": "Hình thức nhan đề khác",
    "250": "Lần xuất bản",
    "260": "Thông tin xuất bản, phân phối",
    "264": "Thông tin xuất bản, phân phối, sản xuất",
    "300": "Mô tả vật lý",
    "336": "Loại hình nội dung",
    "337": "Loại hình phương tiện",
    "338": "Loại hình vật mang tin",
    "490": "Tùng thư",
    "500": "Phụ chú chung",
    "504": "Phụ chú thư mục",
    "505": "Phụ chú nội dung",
    "520": "Phụ chú tóm tắt",
    "600": "Đề mục - Tên cá nhân",
    "610": "Đề mục - Tên tập thể",
    "611": "Đề mục - Tên hội nghị",
    "650": "Đề mục - Chủ đề",
    "651": "Đề mục - Địa lý",
    "700": "Tác giả phụ - Tên cá nhân",
    "710": "Tác giả phụ - Tên tập thể",
    "711": "Tác giả phụ - Tên hội nghị",
    "856": "Vị trí và truy cập điện tử",
    "942": "Thông tin biểu ghi Koha",
    "952": "Thông tin bản tài liệu (Item)"
}

for tag, trans in tag_dict.items():
    cursor.execute("UPDATE marc_tag_structure SET liblibrarian=%s, libopac=%s WHERE tagfield=%s", (trans, trans, tag))

sub_dict = {
    "Qualifying information": "Thông tin bổ sung",
    "Terms of availability": "Điều kiện phổ biến",
    "Source": "Nguồn",
    "Record control number": "Số kiểm soát biểu ghi",
    "System control number": "Số kiểm soát hệ thống",
    "Original cataloging agency": "Cơ quan biên mục gốc",
    "Language of cataloging": "Ngôn ngữ biên mục",
    "Transcribing agency": "Cơ quan sao lục",
    "Modifying agency": "Cơ quan chỉnh sửa",
    "Description conventions": "Quy tắc mô tả",
    "Classification number": "Ký hiệu phân loại",
    "Item number": "Ký hiệu sách",
    "Edition information": "Thông tin lần xuất bản",
    "Personal name": "Tên cá nhân",
    "Corporate name or jurisdiction name as entry element": "Tên tập thể",
    "Meeting name or jurisdiction name as entry element": "Tên hội nghị",
    "Uniform title": "Nhan đề đồng nhất",
    "Title": "Nhan đề",
    "Remainder of title": "Phần còn lại của nhan đề",
    "Statement of responsibility, etc.": "Thông tin trách nhiệm",
    "Place of publication, distribution, etc.": "Nơi xuất bản",
    "Name of publisher, distributor, etc.": "Nhà xuất bản",
    "Date of publication, distribution, etc.": "Năm xuất bản",
    "Extent": "Số trang / Số lượng",
    "Other physical details": "Đặc điểm vật lý khác",
    "Dimensions": "Kích thước",
    "General note": "Phụ chú chung",
    "Bibliography, etc. note": "Phụ chú thư mục",
    "Formatted contents note": "Phụ chú nội dung",
    "Summary, etc.": "Tóm tắt",
    "Topical term or geographic name entry element": "Chủ đề / Tên địa lý",
    "Form subdivision": "Phân mục hình thức",
    "General subdivision": "Phân mục chung",
    "Chronological subdivision": "Phân mục thời gian",
    "Geographic subdivision": "Phân mục địa lý",
    "Uniform Resource Identifier": "Đường dẫn (URL / URI)",
    "Link text": "Văn bản hiển thị liên kết",
    "Barcode": "Mã vạch (Barcode)",
    "Home branch": "Thư viện sở hữu",
    "Holding branch": "Thư viện hiện tại",
    "Item type": "Loại tài liệu",
    "Collection code": "Mã bộ sưu tập",
    "Call number": "Ký hiệu xếp giá",
    "Cost, normal purchase price": "Giá tiền",
    "Date acquired": "Ngày bổ sung",
    "CONTROL NUMBER IDENTIFIER": "Chỉ danh số kiểm soát",
    "DATE AND TIME OF LATEST TRANSACTION": "Ngày giờ giao dịch gần nhất",
    "FIXED-LENGTH DATA ELEMENTS--ADDITIONAL MATERIAL CHARACTERISTICS": "Đặc trưng tài liệu bổ sung",
    "PHYSICAL DESCRIPTION FIXED FIELD--GENERAL INFORMATION": "Trường cố định mô tả vật lý - Thông tin chung",
    "FIXED-LENGTH DATA ELEMENTS--GENERAL INFORMATION": "Các yếu tố độ dài cố định - Thông tin chung",
    "LIBRARY OF CONGRESS CONTROL NUMBER": "Số kiểm soát LC",
    "LC control number": "Số kiểm soát LC",
    "NATIONAL BIBLIOGRAPHY NUMBER": "Số thư mục quốc gia",
    "National bibliography number": "Số thư mục quốc gia",
    "NATIONAL BIBLIOGRAPHIC AGENCY CONTROL NUMBER": "Số kiểm soát cơ quan thư mục quốc gia",
    "INTERNATIONAL STANDARD BOOK NUMBER": "Số ISBN",
    "International Standard Book Number": "Số ISBN",
    "INTERNATIONAL STANDARD SERIAL NUMBER": "Số ISSN",
    "International Standard Serial Number": "Số ISSN",
    "OTHER STANDARD IDENTIFIER": "Mã tiêu chuẩn khác",
    "Standard number or code": "Mã hoặc số tiêu chuẩn",
    "Additional codes following the standard number or code": "Mã bổ sung",
    "STANDARD TECHNICAL REPORT NUMBER": "Số báo cáo kỹ thuật chuẩn",
    "PUBLISHER OR DISTRIBUTOR NUMBER": "Số của nhà phát hành",
    "SYSTEM CONTROL NUMBER": "Số kiểm soát hệ thống",
    "SOURCE OF ACQUISITION": "Nguồn bổ sung",
    "CATALOGING SOURCE": "Nguồn biên mục",
    "LANGUAGE CODE": "Mã ngôn ngữ",
    "TIME PERIOD OF CONTENT": "Khoảng thời gian của nội dung",
    "FORM OF MUSICAL COMPOSITION CODE": "Mã hình thức tác phẩm âm nhạc",
    "NUMBER OF MUSICAL INSTRUMENTS OR VOICES CODE": "Mã nhạc cụ hoặc giọng hát",
    "LIBRARY OF CONGRESS CALL NUMBER": "Ký hiệu phân loại LC",
    "GPO ITEM NUMBER": "Số tài liệu GPO",
    "DEWEY DECIMAL CLASSIFICATION NUMBER": "Ký hiệu phân loại DDC",
    "GOVERNMENT DOCUMENT CLASSIFICATION NUMBER": "Ký hiệu phân loại tài liệu chính phủ",
    "Dates associated with a name": "Năm sinh, năm mất",
    "Relator term": "Vai trò (Từ nối)",
    "Fuller form of name": "Dạng tên đầy đủ",
    "Subordinate unit": "Đơn vị trực thuộc",
    "Location of meeting": "Địa điểm hội nghị",
    "Date of meeting or treaty signing": "Thời gian tổ chức",
    "Number of part/section/meeting": "Số hiệu phần/hội nghị",
    "Title of a work": "Nhan đề tác phẩm",
    "Medium": "Vật mang tin",
    "Relationship information": "Thông tin liên kết",
    "Form of heading": "Hình thức tiêu đề",
    "Language of a work": "Ngôn ngữ của tác phẩm",
    "Number of part/section of a work": "Số hiệu phần của tác phẩm",
    "Name of part/section of a work": "Tên phần của tác phẩm",
    "Version": "Phiên bản",
    "Date of a work": "Năm của tác phẩm",
    "Miscellaneous information": "Thông tin khác",
    "Affiliation": "Cơ quan công tác",
    "Authority record control number or standard number": "Số kiểm soát biểu ghi",
    "Real World Object URI": "Đường dẫn đối tượng thực tế (URI)",
    "Linkage": "Liên kết",
    "Field link and sequence number": "Trường liên kết và số thứ tự",
    "Control subfield": "Trường con kiểm soát",
    "Attribution qualifier": "Đặc tính định danh",
    "Relationship": "Mối quan hệ",
    "Relator code": "Mã vai trò",
    "Institution to which field applies": "Cơ quan áp dụng"
}

for eng, vn in sub_dict.items():
    cursor.execute("UPDATE marc_subfield_structure SET liblibrarian=%s, libopac=%s WHERE liblibrarian=%s", (vn, vn, eng))

db.commit()
db.close()
print("Dịch MARC21 sang Tiếng Việt hoàn tất.")
