<!-- Authority details modal -->
<div class="modal" id="authorityDetail" tabindex="-1" role="dialog" aria-labelledby="authorityDetailLabel">
 <div class="modal-dialog modal-xl">
 <div class="modal-content">
 <div class="modal-header">
 <h1 class="modal-title" id="authorityDetailLabel"></h1>
 <button aria-label="Thoát" class="btn-close" data-bs-dismiss="modal" type="button"></button>
 </div>
 <div class="modal-body">
 <img src="[% interface | html %]/[% theme | html %]/img/spinner-small.gif" alt="" />
 </div>
 <div class="modal-footer">
 <button type="button" class="btn btn-default" data-bs-dismiss="modal">Thoát</button>
 </div>
 </div>
 </div>
</div>
