<tfoot>
    <tr>
        <td colspan="17" style="text-align: right; font-weight:bold;">Tổng cộng:</td>
        <td id="totaldue" style="text-align: right;"></td>
        <td id="totalfine" style="text-align: right;"></td>
        <td id="totalprice" style="text-align: right;"></td>
        <td colspan="4">
            <div class="date-select">
                <p><label for="newduedate">Ngày hạn gia hạn:</label> <input type="text" size="20" id="newduedate" name="newduedate" value="" class="flatpickr" data-flatpickr-enable-time="true" /></p>
                <p id="newonholdduedate"
                    ><label for="newonholdduedatefield">Ngày hạn đặt trước:</label> <input type="text" size="20" name="newonholdduedate" value="" id="newonholdduedatefield" class="flatpickr" data-flatpickr-enable-time="true"
                /></p>
                <p><label for="exemptfine">Miễn phạt khi trả:</label> <input type="checkbox" id="exemptfine" name="exemptfine" value="1" /></p>
            </div>
        </td>
    </tr>
</tfoot>
