<div id="labels-menu" class="sidebar_menu">
 <ul>
 <li><a href="/cgi-bin/koha/labels/label-manage.pl?label_element=batch">Label batches</a></li>
 <li><a href="/cgi-bin/koha/labels/label-manage.pl?label_element=layout">Label layouts</a></li>
 <li><a href="/cgi-bin/koha/labels/label-manage.pl?label_element=template">Hình thức nhãn gáy</a></li>
 <li><a href="/cgi-bin/koha/labels/label-manage.pl?label_element=profile">Mẫu in</a></li>
 <li><a href="/cgi-bin/koha/labels/label-edit-range.pl">Print barcode range</a></li>
 </ul>
</div>
<!-- /.sidebar_menu -->
