<!-- Batch modify hold error modal -->
<div class="modal fade" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="errorModalLabel">
 <div class="modal-dialog">
 <div class="modal-content">
 <div class="modal-header">
 <h1 class="modal-title" id="errorModalLabel">Errors</h1>
 <button aria-label="Thoát" class="btn-close" data-bs-dismiss="modal" type="button"></button>
 </div>
 <div class="modal-body">
 <ul id="errorList"></ul>
 </div>
 <div class="modal-footer">
 <button type="button" class="btn btn-primary" data-bs-dismiss="modal">OK</button>
 </div>
 </div>
 </div>
</div>
