<!-- Delete Vendor modal form -->
<div id="deleteVendorModal" class="modal" tabindex="-1" role="dialog" aria-labelledby="deleteVendorModalLabel">
 <form id="deleteVendorForm">
 <input type="hidden" name="booksellerid" id="booksellerid" value="" />
 <div class="modal-dialog" role="document">
 <div class="modal-content">
 <div class="modal-header">
 <h4 class="modal-title" id="deleteVendorModalLabel">Xóa nhà cung cấp</h4>
 <button aria-label="Thoát" class="btn-close" data-bs-dismiss="modal" type="button"></button>
 </div>
 <div class="modal-body">
 <p>Bạn chắc chắn muốn xóa nhà cung cấp?</p>
 </div>
 <div class="modal-footer">
 <button type="submit" id="deleteVendorModaConfirmBtn" class="btn btn-default approve"><i class="fa fa-check" aria-hidden="true"></i> Có</button>
 <button type="button" id="deleteVendorModaCancelBtn" data-bs-dismiss="modal" class="btn btn-default deny"><i class="fa fa-times" aria-hidden="true"></i> Không</button>
 </div>
 </div>
 </div>
 </form>
</div>
