<div id="toolbar" class="btn-toolbar">
    <div class="btn-group">
        <button class="btn btn-default dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa fa-plus"></i> Thêm mới</button>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/cgi-bin/koha/labels/label-edit-batch.pl?op=new"><i class="fa fa-list-ul"></i> Tạo lô nhãn mới</a></li>
            <li><a class="dropdown-item" href="/cgi-bin/koha/labels/label-edit-layout.pl?op=new"><i class="fa fa-object-group"></i> Tạo bố cục nhãn mới</a></li>
            <li><a class="dropdown-item" href="/cgi-bin/koha/labels/label-edit-template.pl?op=new"><i class="fa fa-table-cells"></i> Tạo mẫu phôi nhãn mới</a></li>
            <li><a class="dropdown-item" href="/cgi-bin/koha/labels/label-edit-profile.pl?op=new"><i class="fa fa-print"></i> Thêm cấu hình máy in</a></li>
        </ul>
    </div>
</div>
